server:
  port: 8761                      # Eureka \u670D\u52A1\u76D1\u542C\u7684\u7AEF\u53E3
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false        # \u4E0D\u5728 Eureka \u670D\u52A1\u4E2D\u6CE8\u518C
    fetch-registry: false              # \u4E0D\u672C\u5730\u7F13\u5B58\u4E2D\u6CE8\u518C\u4FE1\u606F
    service-url:                       # Eureka \u670D\u52A1\u5730\u5740
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
